# Generated by Django 3.2.5 on 2021-08-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
